server:
  port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dbtest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
        username: root
        password: Root-yuan123@
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 10
        initialSize: 1
        maxWait: 60000
        minIdle: 1

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml    #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: springboot.entity  # 注意：对应实体类的路径
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true